/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#00201a',
        'on-error': '#690005',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'on-surface': '#e5e2e1',
        'error-container': '#93000a',
        'on-primary-fixed': '#001d36',
        'on-tertiary-fixed-variant': '#693b27',
        'inverse-on-surface': '#303030',
        'inverse-surface': '#e5e2e1',
        'surface-container-low': '#1b1b1c',
        surface: '#131313',
        'secondary-fixed-dim': '#61dac1',
        'primary-fixed': '#d1e4ff',
        error: '#ffb4ab',
        'secondary-container': '#13a38b',
        'on-surface-variant': '#c0c7d3',
        'tertiary-fixed-dim': '#fab79d',
        'surface-variant': '#353535',
        'on-primary-container': '#ffffff',
        outline: '#8a919d',
        'inverse-primary': '#0061a4',
        'on-secondary-container': '#003028',
        'surface-tint': '#9fcaff',
        background: '#131313',
        'on-error-container': '#ffdad6',
        'on-primary': '#003258',
        'on-secondary': '#00382e',
        'surface-container': '#202020',
        'on-tertiary': '#4e2513',
        'tertiary-container': '#a06952',
        'on-tertiary-container': '#ffffff',
        'surface-container-high': '#2a2a2a',
        'outline-variant': '#404751',
        'on-primary-fixed-variant': '#00497d',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed': '#341103',
        primary: '#9fcaff',
        tertiary: '#fab79d',
        'on-secondary-fixed-variant': '#005144',
        'surface-container-highest': '#353535',
        'tertiary-fixed': '#ffdbcd',
        secondary: '#61dac1',
        'primary-container': '#007acc',
        'primary-fixed-dim': '#9fcaff',
        'secondary-fixed': '#80f7dc',
        'on-background': '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Space Grotesk', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
