version: '3.9'

services:
  caddy:
    image: caddy:latest
    ports:
      - "8181:80"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NOTION_API_KEY: ${NOTION_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
