version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
